## Data Cleaning
Tujuan: Membersihkan dan menyiapkan data sebelum digunakan.

## 1. Loading

Pertama, kita perlu mengambil data.

In [5]:
import pandas as pd

In [6]:
results = pd.read_csv("../data/raw/results.csv")
former_names = pd.read_csv("../data/raw/former_names.csv")
goalscorers = pd.read_csv("../data/raw/goalscorers.csv")
shootouts = pd.read_csv("../data/raw/shootouts.csv")

## 2. Informasi Umum Data

Kemudian, kita akan melihat beberapa informasi umum dari tabel data.

## 2.1 Tabel Results

Kita akan mengecek tabel `results`.

In [14]:
# BENTUK TABEL
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [15]:
# INFORMASI UMUM
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  str
 1   home_team   49477 non-null  str
 2   away_team   49477 non-null  str
 3   home_score  49433 non-null  float64
 4   away_score  49433 non-null  float64
 5   tournament  49477 non-null  str
 6   city        49477 non-null  str
 7   country     49477 non-null  str
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB

Tipe data terlihat normal selain kolom `date`. Kolom `date` masih mempunyai format string, sehingga harus diubah nanti.

In [17]:
# MISSING VALUE
results.isna().sum()

date           0
home_team      0
away_team      0
home_score    44
away_score    44
tournament     0
city           0
country        0
neutral        0
dtype: int64

Tampaknya terdapat data kosong dengan rincian berikut:
- `home_score` : 44 data kosong
- `away_score` : 44 data kosong

In [18]:
# DUPLIKAT
results.duplicated().sum()

np.int64(0)

## 2.2 Tabel Former Names

In [20]:
# BENTUK TABEL
former_names.head()

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

In [22]:
# INFORMASI UMUM
former_names.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   current     36 non-null     str
 1   former      36 non-null     str
 2   start_date  36 non-null     str
 3   end_date    36 non-null     str
dtypes: str(4)
memory usage: 1.3 KB

Kasus yang sama dengan tabel `results`, tabel ini memiliki tanggal (`start_date` dan `end_date`) dengan tipe string.

In [23]:
# MISSING VALUE
former_names.isna().sum()

current       0
former        0
start_date    0
end_date      0
dtype: int64

Tidak ada data kosong.

In [24]:
# DUPLIKAT
former_names.duplicated().sum()

np.int64(0)

Tidak ada data duplikat.